[package]
name = "prisma-cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.203" }
prisma-client-rust = { workspace = true }
prisma-client-rust-cli = { workspace = true }
